
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1405189
 */
public class MyDetails extends javax.swing.JFrame {

    /**
     * Creates new form MyDetails
     */
    public MyDetails() {
        
        initComponents();
        usertf.setText(LOG.userid);
        usertf.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usertf = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        billnotf = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        producttab = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1650, 1080));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel1.setText("BHAI BHAI TRADERS..");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 30, 230, 64);
        getContentPane().add(usertf);
        usertf.setBounds(880, 110, 150, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Slno", "Billno", "Date", "amount"
            }
        ));
        jTable2.setPreferredSize(new java.awt.Dimension(100, 60));
        jScrollPane4.setViewportView(jTable2);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(820, 210, 351, 104);

        jButton3.setText("SHOW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1060, 110, 80, 30);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Slno", "billno", "Date", "amount"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(830, 420, 351, 101);

        jButton2.setText("SHOW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(500, 210, 80, 30);
        getContentPane().add(billnotf);
        billnotf.setBounds(320, 210, 150, 30);

        producttab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SNO", "Product", "Rate", "Quantity", "Amount"
            }
        ));
        jScrollPane2.setViewportView(producttab);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(100, 290, 556, 130);

        jLabel2.setText("BILL NO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 220, 50, 20);

        jLabel3.setText("User_id");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(800, 110, 70, 30);

        jLabel4.setText("Credit");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(820, 170, 80, 30);

        jLabel5.setText("Debit");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(840, 380, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model1 =(DefaultTableModel)jTable2.getModel();
        DefaultTableModel model2 =(DefaultTableModel)jTable3.getModel();

        model1.setRowCount(0);
        model2.setRowCount(0);
        int Sno1=0;
        int Sno2=0;
        String userid=LOG.userid;
        
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","akash","akash1780");
            if(con!=null)
            {
                // System.out.println("Connected to database");
            }
            else
            {
                // System.out.println("Error in connection");
            }
            Statement s =con.createStatement();
            ResultSet r=s.executeQuery("select billno,dates,total from bills where name ='"+userid+"'and modes='credit'");
            while(r.next()){
                Sno1=Sno1+1;
                String Sno=""+Sno1;
                String Billno=r.getString("billno");
                String date=r.getString("dates");
                String Amount=r.getString("total");

                model1.addRow(new Object[]{Sno,Billno,date,Amount});
            }
            r.close();
            s.close();
            con.close();

        }catch(Exception e){System.out.println(e);}
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","akash","akash1780");
            if(con!=null)
            {
                // System.out.println("Connected to database");
            }
            else
            {
                // System.out.println("Error in connection");
            }
            Statement stmt =con.createStatement();
            ResultSet r=stmt.executeQuery("select billno,dates,amount from debit where name ='"+userid+"'");
            while(r.next()){
                Sno2=Sno2+1;
                String Sno=""+Sno2;
                String Billno=r.getString("billno");
                String date=r.getString("dates");
                String Amount=r.getString("amount");

                model2.addRow(new Object[]{Sno,Billno,date,Amount});
            }
            r.close();
            stmt.close();
            con.close();

        }catch(Exception e){System.out.println(e);}

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel)producttab.getModel();
        model.setRowCount(0);
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","akash","akash1780");
            if(con!=null)
            {
                // System.out.println("Connected to database");
            }
            else
            {
                // System.out.println("Error in connection");
            }
            int b=Integer.parseInt(billnotf.getText().toString());
            Statement s =con.createStatement();
             Statement stmt =con.createStatement();
             Statement stmt1 =con.createStatement();
               ResultSet rst=stmt1.executeQuery("select name from debit where billno ="+b+"");
            ResultSet rs=stmt.executeQuery("select name from bills where billno ="+b+"");
            rs.next();
            rst.next();
            String user=usertf.getText();
            String uid=rs.getString("name");
            if(user.equals(uid)){
            int sno1=0;
            ResultSet r=s.executeQuery("select product,rate,quantity,amount from billdetails where billno ="+b+"");
            while(r.next()){
                sno1=sno1+1;
                String Sno=""+sno1;
                String product=r.getString("product");
                String rate=r.getString("rate");
                String quantity=r.getString("quantity");
                String Amount=r.getString("amount");

                model.addRow(new Object[]{Sno,product,rate,quantity,Amount});
            }
            
//            else if(user.equals(rst.getString("name"))){
//             while(rst.next()){
//                 int sno1=0;
//                 ResultSet r=s.executeQuery("select amount from debit where billno ="+b+"");
//                sno1=sno1+1;
//                String Sno=""+sno1;
//                String product="0";
//                String rate="0";
//                String quantity="0";
//                String Amount=rst.getString("amount");
//
//                model.addRow(new Object[]{Sno,product,rate,quantity,Amount});
//            }
            rs.close();
            stmt.close();
            rst.close();
            stmt1.close();
            r.close();
            s.close();
            con.close();
            }
            else{
                 JOptionPane.showMessageDialog(null, "NOT YOUR BILL NO.");
            }

        }catch(Exception e){System.out.println(e);}

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyDetails().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField billnotf;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable producttab;
    private javax.swing.JTextField usertf;
    // End of variables declaration//GEN-END:variables
}
