
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1405180
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    /*public NewJFrame() {
        initComponents();
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billtable = new javax.swing.JTable();
        totaltf = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        billtf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        datetf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        addrow = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1650, 1080));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel1.setText("BHAI BHAI TRADERS..");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(550, 30, 228, 64);
        getContentPane().add(nametf);
        nametf.setBounds(100, 180, 151, 30);

        jRadioButton1.setText("cash");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(1060, 170, 70, 30);

        jRadioButton2.setText("credit");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(1150, 170, 70, 30);

        jLabel2.setText("NAME::");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 180, 50, 20);

        billtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sno", "PRODUCT", "RATE", "QUANTITY", "AMOUNT"
            }
        ));
        jScrollPane1.setViewportView(billtable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(350, 250, 622, 130);

        totaltf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltfActionPerformed(evt);
            }
        });
        getContentPane().add(totaltf);
        totaltf.setBounds(850, 390, 130, 40);

        jButton3.setText("DEBIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(740, 500, 70, 40);

        jButton4.setText("HOME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 110, 200, 30);

        jButton5.setText("CUSTOMER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(260, 110, 250, 30);

        jButton6.setText("LIST");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(560, 110, 210, 30);

        jButton7.setText("LEDGER");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(820, 110, 200, 30);

        jButton8.setText("STOCK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(1060, 110, 190, 30);

        jLabel4.setText("BILL NO::");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 184, 60, 20);

        billtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billtfActionPerformed(evt);
            }
        });
        getContentPane().add(billtf);
        billtf.setBounds(430, 180, 160, 30);

        jLabel5.setText("DATE::");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(730, 180, 60, 30);

        datetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datetfActionPerformed(evt);
            }
        });
        getContentPane().add(datetf);
        datetf.setBounds(810, 180, 120, 30);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 500, 80, 40);

        addrow.setText("Add Row");
        addrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrowActionPerformed(evt);
            }
        });
        getContentPane().add(addrow);
        addrow.setBounds(350, 390, 120, 30);

        jButton9.setText("Total");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(760, 390, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
this.setVisible(false);
new customer().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
this.setVisible(false);
new list().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
this.setVisible(false);
new today().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
this.setVisible(false);
new stock().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   this.setVisible(false);
new debit().setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void billtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billtfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String name,date,product,bno,mode,qury,qur,tot,qury1;
      //int tot;
    //  String billno,slno,quantity,rate,amount,mode;
      int total=0;
       bno=billtf.getText();
       name=nametf.getText();
       date=datetf.getText();
       tot=totaltf.getText();
       //Date d=new Date();
       // SimpleDateFormat s=new SimpleDateFormat("dd-MMM-yy");
     /*  try{
       Date dt = date;
       System.out.println(dt);
       }catch(Exception e){}*/
     
       if (jRadioButton1.isSelected())
      {
          mode="cash";
      }
      else mode="credit";
       qur="insert into bills values("+bno+",'"+name+"','"+mode+"','"+date+"',"+tot+")";
       try{
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","akash","akash1780");
                Statement stmt =con.createStatement();
                stmt.executeQuery(qur);
                stmt.executeQuery("commit");
               // stmt.executeQuery("commit");
            }catch(Exception e){System.out.println(e);}
       /* try
        {
          Class.forName("oracle.jdbc.driver.OracleDriver");
          Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","akash","akash1780");
       
          Statement s =con.createStatement();
      
          s.executeQuery("insert into bill values(billno,name,date,slno,product,rate,quantity,amount,mode)");
          con.close();
        }catch(Exception e){System.out.println(e);}*/
        
        //DefaultTableModel table=(DefaultTableModel)billtable.getModel();
        int r=billtable.getRowCount();
        int i,j;
        int arr[];
        arr=new int[5];
      
        int sno,Rate,Quan,Amt,Quan1;
        String prod;
       System.out.println(bno+"\t"+name+"\t"+mode+"\t"+date);
        for(i=0;i<r;i++)
        {
          
           if(billtable.getValueAt(i,1)!=null)
           {
            sno=Integer.parseInt(billtable.getValueAt(i,0).toString()) ;
            product=billtable.getValueAt(i,1).toString();
            Rate=Integer.parseInt(billtable.getValueAt(i,2).toString()) ;
            Quan=Integer.parseInt(billtable.getValueAt(i,3).toString()) ;
            Amt=Rate*Quan;
            
            total=total+Amt;
           // Amt=Integer.parseInt(billtable.getValueAt(i,4).toString()) ;
           // System.out.println(arr[0]+"\t"+prod+"\t"+arr[1]+"\t"+arr[2]+"\t"+arr[3]);
            try{       
          
                ResultSet rs=null,rs1;
                Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","akash","akash1780");
                Statement stmt =con.createStatement();
                Statement stmt1 =con.createStatement();
                Statement stmt2=con.createStatement();
                 rs=stmt.executeQuery("select serialno.nextval from dual ");
             // System.out.println("asda");
          rs.next();
          int srno=rs.getInt(1);
        //  System.out.println(srno+"\t");
         // System.out.println(bno+"\t");
            qury="INSERT INTO BILLDETAILS(slno,billno,product,rate,quantity,amount) VALUES"
                    + "("+srno+","+bno+",'"+product+"',"+Rate+","+Quan+","+Amt+")";
            rs1=stmt1.executeQuery("select quantity from stock where product='"+product+"'");
            rs1.next();
            System.out.println(Quan);
            String Quan2=rs1.getString("QUANTITY");
            System.out.println(Quan2);
            Quan1=Integer.parseInt(Quan2);
            Quan1=Quan1-Quan;
            System.out.println(Quan1);
            qury1="update stock set quantity="+Quan1+" where product='"+product+"'";
                stmt.executeQuery(qury);
                stmt.executeQuery("commit");
                 stmt2.executeQuery(qury1);
                stmt2.executeQuery("commit");
                
            }catch(Exception e){System.out.println(e);}
            getMax();
            nametf.setText("");
           // DefaultTableModel model = (DefaultTableModel) billtable.getModel();
           // deleteAllRows(model);
        
          // System.out.println(sno+"\t"+product+"\t"+Rate+"\t"+Quan+"\t"+Amt);
           }
        }
        DefaultTableModel model=(DefaultTableModel)billtable.getModel();
        int k;
       for(k=0;k<billtable.getRowCount();k++)
       {
           for(j=1;j<billtable.getColumnCount();j++)
               model.setValueAt(null, k, j);
               
       }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void datetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datetfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datetfActionPerformed

    private void addrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrowActionPerformed
            // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)billtable.getModel();
        Object[] row={null,null,null,null,null};
        model.addRow(row);
        int r=billtable.getRowCount();
        model.setValueAt(r, r-1, 0);
    }//GEN-LAST:event_addrowActionPerformed

    private void totaltfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaltfActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int i,Rate,Quan,Amt,total=0;
        
        DefaultTableModel model=(DefaultTableModel)billtable.getModel();
        int r=model.getRowCount();
         for(i=0;i<r;i++)
        {
          
           if(billtable.getValueAt(i,1)!=null)
           {
            Rate=Integer.parseInt(billtable.getValueAt(i,2).toString()) ;
            Quan=Integer.parseInt(billtable.getValueAt(i,3).toString()) ;
            Amt=Rate*Quan;
            
            total=total+Amt;
           }
        }
        totaltf.setText(""+total);
        
    }//GEN-LAST:event_jButton9ActionPerformed
void setSerial()
{
    int i;
    int r=billtable.getRowCount();
    DefaultTableModel model=(DefaultTableModel)billtable.getModel();
   // Object []row={null};
    for(i=0;i<r;i++)
    {
        
      model.setValueAt(i+1, i, 0);
    }
}        
        
        
/*public  final String Datefo="dd-mm-yy";
    /**
     * @param args the command line arguments
     */
    public NewJFrame(){
        initComponents();
        showDate();
        getMax();
        setSerial();
        
    }
    void showDate()
    {
        Date d=new Date();
        SimpleDateFormat s=new SimpleDateFormat("dd-MMM-yy");
        datetf.setText(s.format(d));
    }
    public static void deleteAllRows(final DefaultTableModel model)
    { 
        for( int i = model.getRowCount() - 1; i >= 0; i-- )
        { model.removeRow(i); } 
    }
   /* void showBill()
    {
       try
        { 
          Class.forName("oracle.jdbc.driver.OracleDriver");
          Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","akash","akash1780");
          Statement s =con.createStatement();
         String sql="select BILLNO from bill" ;
         
          ResultSet r=s.executeQuery(sql);
          r.next();
       int b= r.getInt(1);
       String v=""+b;
         billtf.setText(v);
         r.close();
         s.close();
          con.close();
         // billtf.setText("aka");
        }catch(Exception e){
            System.out.println(e);
            billtf.setText("exe");
            
            
        }
        //billtf.setText(""+r.getString(1));
    }*/
    public void getMax()
    {
        String strng=null;
       try
        { 
       //  Class.forName("oracle.jdbc.driver.OracleDriver");
         Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","akash","akash1780");
         Statement s =con.createStatement();
         //sql="select BILLNO from bill" ;
         
          ResultSet rs=s.executeQuery("select billno from bills order by billno desc ");
             // System.out.println("asda");
  rs.next();
  //rs.next();
          // String x=r.getString("BILLNO");
             // System.out.println(r.getString(1));
               int b=rs.getInt(1);
               
                    ResultSet rs1=s.executeQuery("select billno from debit order by billno desc ");
               rs1.next();
               int b1=rs1.getInt(1);
               if(b>b1)
                   b=b+1;
               else b=b1+1;    
               strng=""+b;
               billtf.setText(strng);
          
       //int b= r.getInt("BILLNO");
     //System.out.println(b);
       //String v=r.toString();
      // billtf.setText(""+r.getInt("BILLNO"));
        // r.close();
        // s.close();
          con.close();
       }
       catch(Exception e)
       {
            System.out.println(e);
           billtf.setText("exe");
        }
        
    }
    public static void main(String args[])throws Exception {
        
      
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addrow;
    private javax.swing.JTable billtable;
    private javax.swing.JTextField billtf;
    private javax.swing.JTextField datetf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nametf;
    private javax.swing.JTextField totaltf;
    // End of variables declaration//GEN-END:variables
 
    
   


}
/*public class NewJFrame extends javax.swing.JFrame{
    public NewJFrame(){
        initComponents();
        showDate();
    }
    void showDate()
    {
        Date d=new Date();
        SimpleDateFormat s=new SimpleDateFormat("dd-MM-yy");
        datetf.setText(s.format(d));
    }
}*/

