
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1405180
 */
public class today extends javax.swing.JFrame {

    /**
     * Creates new form today
     */
    public today() {
        initComponents();
        //setframe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        datestf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ledgertable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        producttab = new javax.swing.JTable();
        billnotf = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        usertf = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1650, 1080));
        getContentPane().setLayout(null);

        jButton8.setText("STOCK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(1060, 140, 200, 30);

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel1.setText("BHAI BHAI TRADERS..");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(560, 40, 228, 64);

        jButton4.setText("HOME");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(30, 140, 220, 30);

        jButton5.setText("CUSTOMER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(290, 140, 240, 30);

        jButton6.setText("LIST");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(570, 140, 210, 30);

        jButton7.setText("LEDGER");
        getContentPane().add(jButton7);
        jButton7.setBounds(810, 140, 220, 30);

        jLabel2.setText("DATED");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 280, 50, 30);
        getContentPane().add(datestf);
        datestf.setBounds(150, 280, 130, 30);

        jButton1.setText("SHOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 280, 90, 30);

        ledgertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sno", "Billno", "Mode", "Name", "Total Amount"
            }
        ));
        jScrollPane1.setViewportView(ledgertable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 330, 520, 130);

        producttab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "SNO", "Product", "Rate", "Quantity", "Amount"
            }
        ));
        jScrollPane2.setViewportView(producttab);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(90, 550, 515, 101);
        getContentPane().add(billnotf);
        billnotf.setBounds(150, 500, 150, 30);

        jButton2.setText("SHOW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 510, 90, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Slno", "Billno", "Date", "amount"
            }
        ));
        jTable2.setPreferredSize(new java.awt.Dimension(100, 60));
        jScrollPane4.setViewportView(jTable2);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(800, 380, 370, 104);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Slno", "billno", "Date", "amount"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(800, 550, 380, 101);
        getContentPane().add(usertf);
        usertf.setBounds(850, 280, 140, 30);

        jButton3.setText("SHOW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1100, 280, 70, 30);

        jLabel3.setText("Bill NO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 510, 50, 20);

        jLabel4.setText("User_id");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(800, 280, 60, 30);

        jLabel5.setText("Credit");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(800, 340, 60, 30);

        jLabel6.setText("Debit");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(800, 510, 60, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model1 =(DefaultTableModel)jTable2.getModel();
        DefaultTableModel model2 =(DefaultTableModel)jTable3.getModel();

        model1.setRowCount(0);
        model2.setRowCount(0);
        int Sno1=0;
        int Sno2=0;
        String userid=usertf.getText();
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","akash","akash1780");
            if(con!=null)
            {
                // System.out.println("Connected to database");
            }
            else
            {
                // System.out.println("Error in connection");
            }
            Statement s =con.createStatement();
            ResultSet r=s.executeQuery("select billno,dates,total from bills where name ='"+userid+"'and modes='credit'");
            while(r.next()){
                Sno1=Sno1+1;
                String Sno=""+Sno1;
                String Billno=r.getString("billno");
                String date=r.getString("dates");
                String Amount=r.getString("total");

                model1.addRow(new Object[]{Sno,Billno,date,Amount});
            }
            r.close();
            s.close();
            con.close();

        }catch(Exception e){System.out.println(e);}
            try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","akash","akash1780");
            if(con!=null)
            {
                // System.out.println("Connected to database");
            }
            else
            {
                // System.out.println("Error in connection");
            }
            Statement stmt =con.createStatement();
            ResultSet r=stmt.executeQuery("select billno,dates,amount from debit where name ='"+userid+"'");
            while(r.next()){
                Sno2=Sno2+1;
                String Sno=""+Sno2;
                String Billno=r.getString("billno");
                String date=r.getString("dates");
                String Amount=r.getString("amount");

                model2.addRow(new Object[]{Sno,Billno,date,Amount});
            }
            r.close();
            stmt.close();
            con.close();

        }catch(Exception e){System.out.println(e);}
            

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel)producttab.getModel();
        model.setRowCount(0);
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","akash","akash1780");
            if(con!=null)
            {
                // System.out.println("Connected to database");
            }
            else
            {
                // System.out.println("Error in connection");
            }
            int b=Integer.parseInt(billnotf.getText().toString());
            Statement s =con.createStatement();
            Statement stmt =con.createStatement();
            int sno1=0;
            ResultSet r=s.executeQuery("select product,rate,quantity,amount from billdetails where billno ="+b+"");
            ResultSet rs=stmt.executeQuery("select amount from debit where billno ="+b+"");
            while(r.next()){
                sno1=sno1+1;
                String Sno=""+sno1;
                String product=r.getString("product");
                String rate=r.getString("rate");
                String quantity=r.getString("quantity");
                String Amount=r.getString("amount");

                model.addRow(new Object[]{Sno,product,rate,quantity,Amount});
            }
             while(rs.next()){
                sno1=sno1+1;
                String Sno=""+sno1;
                String product="0";
                String rate="0";
                String quantity="0";
                String Amount=rs.getString("amount");

                model.addRow(new Object[]{Sno,product,rate,quantity,Amount});
            }
            r.close();
            s.close();
             rs.close();
            stmt.close();
            con.close();

        }catch(Exception e){System.out.println(e);}
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model =(DefaultTableModel)ledgertable.getModel();
        model.setRowCount(0);
        int Sno1=0;
        String dates=datestf.getText();
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","akash","akash1780");
            if(con!=null)
            {
                // System.out.println("Connected to database");
            }
            else
            {
                // System.out.println("Error in connection");
            }
            Statement s =con.createStatement();
            Statement stmt =con.createStatement();
            ResultSet r=s.executeQuery("select billno,modes,name,total from bills where dates ='"+dates+"'");
             ResultSet rs=stmt.executeQuery("select billno,name,amount from debit where dates ='"+dates+"'");
            while(r.next()){
               // if(r.next())
                //{
                Sno1=Sno1+1;
                String Sno=""+Sno1;
                String Billno=r.getString("billno");
                String Mode=r.getString("modes");
                String Name=r.getString("name");
                String Amount=r.getString("total");
                model.addRow(new Object[]{Sno,Billno,Mode,Name,Amount});
            }
                while(rs.next())
                {
                Sno1=Sno1+1;
                String Sno=""+Sno1;
                String Billno=rs.getString("billno");
                String Mode="DEBIT";
                String Name=rs.getString("name");
                String Amount=rs.getString("amount");
                model.addRow(new Object[]{Sno,Billno,Mode,Name,Amount});}

                
            
            rs.close();
            stmt.close();
            r.close();
            s.close();
            con.close();

        }catch(Exception e){System.out.println(e);}         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
        new list().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        new customer().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        new NewJFrame().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.setVisible(false);
        new stock().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(today.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(today.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(today.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(today.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new today().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField billnotf;
    private javax.swing.JTextField datestf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable ledgertable;
    private javax.swing.JTable producttab;
    private javax.swing.JTextField usertf;
    // End of variables declaration//GEN-END:variables
}
